### ISSUE TITLE
Stub Dependency on Auth App

### ISSUE THREAD

**Issue by nelsonic** [dwyl/rbac#18]
As noted in https://github.com/dwyl/rbac/issues/16#issuecomment-935804847 the `rbac` tests have a dependency on the `auth` (Heroku) App. This is obviously undesirable especially when the `auth` App is offline ... 🤦‍♂️ 

# Todo

+ [ ] borrow the idea from "Inject Poison" mocking similar to how we do it in:
https://github.com/dwyl/elixir-auth-github/blob/9740fd3d7f90230d2b5e8f627e8f31b98b97a72b/lib/elixir_auth_github.ex#L17-L19
+ [ ] Completely mock the requests that go to `auth` so that the `rbac` tests run offline.
+ [ ] have the `option` to run the tests in "e2e" mode so that they run integration with `auth`.
+ [ ] Create PR
+ [ ] Publish new version to Hex.pm

This is a "nice to have" once other `priority-1` and `priority-2` tasks are complete.
