### ISSUE TITLE
Get List of Roles for App 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/rbac#3]
In order to allow **_custom_ roles** for any App that uses Auth, we need a way of getting the list of roles that are relevant to that App _once_ during application startup. The list should be cached in memory to speed up in-app role checking. Such that a call to `RBAC.has_role(person, "hotel_guest")` #2 should take **_less_ than a _microsecond_** (_zero network latency_).

# Todo

+ [ ] use `AUTH_API_KEY` to request the list of Roles & Permissions relevant to a given App 
  + [ ] Response should be a `JSON` `Array` of `Objects` similar to [`default_roles.json`](https://github.com/dwyl/auth/blob/c1f9d3b0e102c04d1e82b509a9550f237232bbc1/priv/repo/default_roles.json) which should be decoded/parsed as a `List` of `Maps` in `Elixir` using [`Jason.decode/2`](https://hexdocs.pm/jason/Jason.html#decode/2) (_which means we will need to add it as a dependency_).
+ [ ] cache the List of Roles in memory to avoid any further HTTP requests
+ [ ] Refresh the list when the app is Re-booted.
